[package]
name = "cita-vm"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
cita_trie = "0.1.6"
crossbeam = "0.4"
env_logger = "0.6.1"
ethereum-types = "0.4.0"
hex = "0.3"
libsecp256k1 = "0.2.2"
log = "0.4.0"
rlp = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha3 = "0.8.0"
tiny-keccak = "1.4.2"
evm = { path="./evm" }
state = { path="./state" }

[workspace]
members = [
    "evm",
    "ewasm",
    "state"
]
