[package]
name = "cita-vm"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
ethereum-types = "0.4.0"
sha3 = "0.8.0"

[workspace]
members = [
    "evm",
    "ewasm",
    "state"
]
