[package]
name = "evmbin"
version = "0.1.0"
authors = ["mohanson <mohanson@outlook.com>"]
edition = "2018"

[dependencies]
ethereum-types = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hex = "0.3"
cita-vm = { path = "../" }
evm = { path="../evm" }
