[package]
name = "state"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
sha3 = "0.8.0"
hex = "0.3.2"
rlp = "0.3.0"
lru-cache = "0.1.1"
ethereum-types = "0.4"
evm = { path="../evm" }
bytes = "0.4.11"
cita_trie = { git = "https://github.com/cryptape/cita-trie.git", branch = "master" }

hash-db = { git = "https://github.com/paritytech/trie", default-features = false }
trie-db = { git = "https://github.com/paritytech/trie", optional = true }
trie-root = { git = "https://github.com/paritytech/trie", default-features = false }
memory-db = { git = "https://github.com/paritytech/trie", optional = true }
hash256-std-hasher = { git = "https://github.com/paritytech/trie", optional = true }

[features]
default = ["std"]
std = [
	"hash-db/std",
	"memory-db",
	"trie-db",
	"trie-root/std",
	"hash256-std-hasher"
]
