[package]
name = "state"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
sha3 = "0.8.0"
hex = "0.3.2"
rlp = "0.3.0"
cita_trie = "0.1.3"
lru-cache = "0.1.1"

cita-types = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
util = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
hashable = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }


[build-dependencies]

[features]
